/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.izzettinozmen.hotelreservation;

import javax.swing.*;

/**
 *
 * @author ifozmen
 */
public class AFRAME extends javax.swing.JFrame {

    /**
     * Creates new form AdDetailsFrame
     */
    public AFRAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnHome2 = new javax.swing.JButton();
        btnUserProf2 = new javax.swing.JButton();
        btnLogOut2 = new javax.swing.JButton();
        btnHotelList2 = new javax.swing.JButton();
        btnAdSettings2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHome2.setText("Home");
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });

        btnUserProf2.setText("Admin Settings");
        btnUserProf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserProf2ActionPerformed(evt);
            }
        });

        btnLogOut2.setText("Log Out");
        btnLogOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut2ActionPerformed(evt);
            }
        });

        btnHotelList2.setText("Hotel List");
        btnHotelList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelList2ActionPerformed(evt);
            }
        });

        btnAdSettings2.setText("Ad Settings");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome2)
                .addGap(52, 52, 52)
                .addComponent(btnHotelList2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserProf2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdSettings2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(btnLogOut2)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHotelList2)
                    .addComponent(btnHome2)
                    .addComponent(btnUserProf2)
                    .addComponent(btnAdSettings2)
                    .addComponent(btnLogOut2))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
        // TODO add your handling code here:
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            String localImagePath = "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png";
            ImageIcon icon = new ImageIcon(new ImageIcon(localImagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        JLabel splashLabel = new JLabel("Loading Home...", JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);
        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);
        Timer timer = new Timer(100, e -> {
            FrameHome hotelMenuFrame = new FrameHome();
            hotelMenuFrame.setVisible(true);
            this.setVisible(false);
            splash.dispose();
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnHome2ActionPerformed

    private void btnUserProf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserProf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserProf2ActionPerformed

    private void btnLogOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOut2ActionPerformed

    private void btnHotelList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelList2ActionPerformed
        // TODO add your handling code here:
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            String localImagePath = "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png";
            ImageIcon icon = new ImageIcon(new ImageIcon(localImagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        JLabel splashLabel = new JLabel("Loading Hotel List...", JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);
        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);
        Timer timer = new Timer(100, e -> {
            FrameHotelList hotelListFrame = new FrameHotelList();
            hotelListFrame.setVisible(true);
            this.setVisible(false);
            splash.dispose();
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnHotelList2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdSettings;
    private javax.swing.JButton btnAdSettings1;
    private javax.swing.JButton btnAdSettings2;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnHotelList;
    private javax.swing.JButton btnHotelList1;
    private javax.swing.JButton btnHotelList2;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogOut1;
    private javax.swing.JButton btnLogOut2;
    private javax.swing.JButton btnUserProf;
    private javax.swing.JButton btnUserProf1;
    private javax.swing.JButton btnUserProf2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
