/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.izzettinozmen.hotelreservation;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.*;

/**
 *
 * @author ifozmen
 */
public class FrameHome extends javax.swing.JFrame {

    /**
     * Creates new form HotelMenu
     */
    public FrameHome() {
        initComponents();
        setLocationRelativeTo(null);

    }

    private void showSplashAndOpen(JFrame targetFrame, String imagePath, String message) {
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            ImageIcon icon = new ImageIcon(new ImageIcon(imagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        JLabel splashLabel = new JLabel(message, JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);

        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);

        Timer timer = new Timer(500, e -> {
            splash.dispose();
            targetFrame.setVisible(true);
            this.setVisible(false);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnShowMore = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();
        panelHotel2 = new javax.swing.JPanel();
        ImageIcon otel2resim = new ImageIcon("/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/otel2.jpg");
        Image imgotel2 = otel2resim.getImage();
        Image scaledImg2 = imgotel2.getScaledInstance(200, 150, Image.SCALE_SMOOTH); // Genişlik ve yükseklik değerlerini belirleyin
        ImageIcon kucukResim2 = new ImageIcon(scaledImg2);
        iconHotel2 = new javax.swing.JLabel();
        txtHotel2 = new javax.swing.JLabel();
        txtDescHotel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRatingHotel2 = new javax.swing.JLabel();
        txtPriceHotel2 = new javax.swing.JLabel();
        btnHotel2 = new javax.swing.JButton();
        panelHotel1 = new javax.swing.JPanel();
        txtHotel1 = new javax.swing.JLabel();
        ImageIcon otel1resim = new ImageIcon("/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/otel1.jpg");
        Image imgotel1 = otel1resim.getImage();
        Image scaledImg1 = imgotel1.getScaledInstance(200, 150, Image.SCALE_SMOOTH); // Genişlik ve yükseklik değerlerini belirleyin
        ImageIcon kucukResim1 = new ImageIcon(scaledImg1);
        iconHotel1 = new javax.swing.JLabel();
        txtDescHotel1 = new javax.swing.JLabel();
        txtRatingHotel1 = new javax.swing.JLabel();
        txtPriceHotel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnHotel1 = new javax.swing.JButton();
        panelHotel3 = new javax.swing.JPanel();
        ImageIcon otel3resim = new ImageIcon("/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/otel3.jpg");
        Image imgotel3 = otel3resim.getImage();
        Image scaledImg3 = imgotel3.getScaledInstance(200, 150, Image.SCALE_SMOOTH); // Genişlik ve yükseklik değerlerini belirleyin
        ImageIcon kucukResim3 = new ImageIcon(scaledImg3);
        iconHotel3 = new javax.swing.JLabel();
        txtHotel3 = new javax.swing.JLabel();
        txtDescHotel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRatingHotel3 = new javax.swing.JLabel();
        txtPriceHotel3 = new javax.swing.JLabel();
        btnHotel3 = new javax.swing.JButton();
        txtFOZGO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnShowRes = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnUserProf = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnResHistory = new javax.swing.JButton();
        btnHotelList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 248));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShowMore.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        btnShowMore.setText("Show More");
        btnShowMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMoreActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowMore, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 690, -1, -1));

        txtWelcome.setFont(new java.awt.Font("Lantinghei TC", 3, 18)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(0, 51, 51));
        txtWelcome.setText("Welcome FOZGO Hotel Reservation ");
        jPanel1.add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, -1, -1));

        panelHotel2.setBackground(new java.awt.Color(255, 251, 248));
        panelHotel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));

        iconHotel2.setIcon(kucukResim2);
        iconHotel2.setText(null);
        iconHotel2.setPreferredSize(new java.awt.Dimension(200, 150));

        txtHotel2.setFont(new java.awt.Font("Lantinghei SC", 1, 18)); // NOI18N
        txtHotel2.setForeground(new java.awt.Color(51, 153, 255));
        txtHotel2.setText("Crystal Bay Lodge");

        txtDescHotel2.setText("<html>Lüks konfor ve tropikal atmosferin buluştuğu tatil.</html>");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Puan:");

        txtRatingHotel2.setForeground(new java.awt.Color(255, 204, 0));
        txtRatingHotel2.setText("9.1");

        txtPriceHotel2.setBackground(new java.awt.Color(0, 0, 0));
        txtPriceHotel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtPriceHotel2.setForeground(new java.awt.Color(0, 0, 0));
        txtPriceHotel2.setText("Fiyat: 1200 TL/gece");

        btnHotel2.setText("Check Hotel");

        javax.swing.GroupLayout panelHotel2Layout = new javax.swing.GroupLayout(panelHotel2);
        panelHotel2.setLayout(panelHotel2Layout);
        panelHotel2Layout.setHorizontalGroup(
            panelHotel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotel2Layout.createSequentialGroup()
                .addGroup(panelHotel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHotel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(iconHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHotel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelHotel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHotel2)
                            .addGroup(panelHotel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRatingHotel2))
                            .addComponent(txtDescHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHotel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panelHotel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPriceHotel2)
                                    .addGroup(panelHotel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnHotel2)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelHotel2Layout.setVerticalGroup(
            panelHotel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHotel2)
                .addGap(18, 18, 18)
                .addComponent(txtDescHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHotel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRatingHotel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPriceHotel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnHotel2)
                .addGap(16, 16, 16))
        );

        iconHotel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconHotel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.add(panelHotel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 240, 420));

        panelHotel1.setBackground(new java.awt.Color(255, 251, 248));
        panelHotel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51), java.awt.Color.yellow, new java.awt.Color(255, 255, 51)));

        txtHotel1.setFont(new java.awt.Font("Lantinghei SC", 1, 18)); // NOI18N
        txtHotel1.setForeground(new java.awt.Color(51, 153, 255));
        txtHotel1.setText("Blue Horizon Suits");

        iconHotel1.setBackground(new java.awt.Color(153, 153, 153));
        iconHotel1.setIcon(kucukResim1);
        iconHotel1.setText(null);
        iconHotel1.setPreferredSize(new java.awt.Dimension(200, 150));

        txtDescHotel1.setText("<html>Eşsiz deniz manzarasıyla huzurun yeni adresi.</html>");

        txtRatingHotel1.setForeground(new java.awt.Color(255, 204, 0));
        txtRatingHotel1.setText("9.3");

        txtPriceHotel1.setBackground(new java.awt.Color(0, 0, 0));
        txtPriceHotel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtPriceHotel1.setForeground(new java.awt.Color(0, 0, 0));
        txtPriceHotel1.setText("Fiyat: 1500 TL/gece");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Puan:");

        btnHotel1.setText("Check Hotel");

        javax.swing.GroupLayout panelHotel1Layout = new javax.swing.GroupLayout(panelHotel1);
        panelHotel1.setLayout(panelHotel1Layout);
        panelHotel1Layout.setHorizontalGroup(
            panelHotel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotel1Layout.createSequentialGroup()
                .addGroup(panelHotel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHotel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(iconHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHotel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelHotel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHotel1)
                            .addGroup(panelHotel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRatingHotel1))
                            .addComponent(txtDescHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHotel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panelHotel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPriceHotel1)
                                    .addGroup(panelHotel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnHotel1)))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelHotel1Layout.setVerticalGroup(
            panelHotel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHotel1)
                .addGap(18, 18, 18)
                .addComponent(txtDescHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHotel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRatingHotel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPriceHotel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnHotel1)
                .addGap(14, 14, 14))
        );

        iconHotel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconHotel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.add(panelHotel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 230, 420));

        panelHotel3.setBackground(new java.awt.Color(255, 251, 248));
        panelHotel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));

        iconHotel3.setBackground(new java.awt.Color(153, 153, 153));
        iconHotel3.setIcon(kucukResim3);
        iconHotel3.setText(null);
        iconHotel3.setPreferredSize(new java.awt.Dimension(200, 150));

        txtHotel3.setFont(new java.awt.Font("Lantinghei SC", 1, 18)); // NOI18N
        txtHotel3.setForeground(new java.awt.Color(51, 153, 255));
        txtHotel3.setText("Starlight Cove Retreat");

        txtDescHotel3.setText("<html>Zümrüt yeşili doğa ve mavinin buluştuğu eşsiz tatil.</html>");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Puan:");

        txtRatingHotel3.setForeground(new java.awt.Color(255, 204, 0));
        txtRatingHotel3.setText("9.5");

        txtPriceHotel3.setBackground(new java.awt.Color(0, 0, 0));
        txtPriceHotel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtPriceHotel3.setForeground(new java.awt.Color(0, 0, 0));
        txtPriceHotel3.setText("Fiyat: 1700 TL/gece");

        btnHotel3.setText("Check Hotel");

        javax.swing.GroupLayout panelHotel3Layout = new javax.swing.GroupLayout(panelHotel3);
        panelHotel3.setLayout(panelHotel3Layout);
        panelHotel3Layout.setHorizontalGroup(
            panelHotel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHotel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelHotel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHotel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtHotel3))
                    .addComponent(iconHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(panelHotel3Layout.createSequentialGroup()
                .addGroup(panelHotel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHotel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelHotel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHotel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtPriceHotel3))
                            .addGroup(panelHotel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRatingHotel3))
                            .addComponent(txtDescHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHotel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnHotel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHotel3Layout.setVerticalGroup(
            panelHotel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHotel3)
                .addGap(18, 18, 18)
                .addComponent(txtDescHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHotel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRatingHotel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPriceHotel3)
                .addGap(17, 17, 17)
                .addComponent(btnHotel3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        iconHotel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconHotel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.add(panelHotel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 240, 420));

        txtFOZGO.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtFOZGO.setForeground(new java.awt.Color(61, 61, 61));
        txtFOZGO.setText("<html> Fozgo olarak size en iyi otelleri sunmaktan gurur duyuyoruz.  Tatilinizde konfor, lüks ve unutulmaz anılar için  dünyanın dört bir yanındaki en iyi seçenekleri bir araya getirdik.<br><br> <b>En iyi fiyatlar:</b> Bütçenize uygun oteller.<br> <b>Kaliteli hizmet:</b> Misafirlerimizin konforu her zaman önceliğimizdir.<br> <b>Kapsamlı seçenekler:</b> Denize sıfır otellerden şehir otellerine kadar geniş yelpazemizle hizmetinizdeyiz.<br><br> Şimdi size uygun oteli seçin ve tatilinize bir adım daha yaklaşın! </html>");
        jPanel1.add(txtFOZGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 790, 150));

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnShowRes.setText("Show Reservations");
        btnShowRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowResActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnUserProf.setText("User Settings");
        btnUserProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserProfActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnResHistory.setText("Reservation History");
        btnResHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResHistoryActionPerformed(evt);
            }
        });

        btnHotelList.setText("Hotel List");
        btnHotelList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome)
                .addGap(52, 52, 52)
                .addComponent(btnHotelList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserProf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowRes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResHistory)
                .addGap(137, 137, 137)
                .addComponent(btnLogOut))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHotelList)
                        .addComponent(btnHome)
                        .addComponent(btnUserProf)
                        .addComponent(btnShowRes)
                        .addComponent(btnResHistory))
                    .addComponent(btnLogOut))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowResActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnUserProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserProfActionPerformed
        // TODO add your handling code here:
        FrameUser adminMenuFrame = new FrameUser();

        showSplashAndOpen(adminMenuFrame,
                "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png",
                "Loading Settings...");
    }//GEN-LAST:event_btnUserProfActionPerformed

    private void btnShowMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMoreActionPerformed
        // TODO add your handling code here:
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            String localImagePath = "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png";
            ImageIcon icon = new ImageIcon(new ImageIcon(localImagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        JLabel splashLabel = new JLabel("Loading Hotel List...", JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);
        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);
        Timer timer = new Timer(100, e -> {
            FrameHotelList hotelListFrame = new FrameHotelList();
            hotelListFrame.setVisible(true);
            this.setVisible(false);
            splash.dispose();
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnShowMoreActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            String localImagePath = "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png";
            ImageIcon icon = new ImageIcon(new ImageIcon(localImagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        JLabel splashLabel = new JLabel("Logging Out...", JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);
        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);
        Timer timer = new Timer(500, e -> {
            FrameLogin loginMenu = new FrameLogin();
            loginMenu.setVisible(true);
            this.setVisible(false);
            splash.dispose();
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnResHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResHistoryActionPerformed

    private void btnHotelListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelListActionPerformed
        // TODO add your handling code here:
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            String localImagePath = "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png";
            ImageIcon icon = new ImageIcon(new ImageIcon(localImagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        JLabel splashLabel = new JLabel("Loading Hotel List...", JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);
        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);
        Timer timer = new Timer(100, e -> {
            FrameHotelList hotelListFrame = new FrameHotelList();
            hotelListFrame.setVisible(true);
            this.setVisible(false);
            splash.dispose();
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnHotelListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MacOS".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHome().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHotel1;
    private javax.swing.JButton btnHotel2;
    private javax.swing.JButton btnHotel3;
    private javax.swing.JButton btnHotelList;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnResHistory;
    private javax.swing.JButton btnShowMore;
    private javax.swing.JButton btnShowRes;
    private javax.swing.JButton btnUserProf;
    private javax.swing.JLabel iconHotel1;
    private javax.swing.JLabel iconHotel2;
    private javax.swing.JLabel iconHotel3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelHotel1;
    private javax.swing.JPanel panelHotel2;
    private javax.swing.JPanel panelHotel3;
    private javax.swing.JLabel txtDescHotel1;
    private javax.swing.JLabel txtDescHotel2;
    private javax.swing.JLabel txtDescHotel3;
    private javax.swing.JLabel txtFOZGO;
    private javax.swing.JLabel txtHotel1;
    private javax.swing.JLabel txtHotel2;
    private javax.swing.JLabel txtHotel3;
    private javax.swing.JLabel txtPriceHotel1;
    private javax.swing.JLabel txtPriceHotel2;
    private javax.swing.JLabel txtPriceHotel3;
    private javax.swing.JLabel txtRatingHotel1;
    private javax.swing.JLabel txtRatingHotel2;
    private javax.swing.JLabel txtRatingHotel3;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
