/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.izzettinozmen.hotelreservation;

import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.JPanel;
import javax.swing.*;

/**
 *
 * @author ifozmen
 */
public class FrameUser extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public FrameUser() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /*
    private void showSplashAndOpen(JFrame targetFrame, String imagePath, String message) {
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            ImageIcon icon = new ImageIcon(new ImageIcon(imagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        JLabel splashLabel = new JLabel(message, JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);

        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);

        Timer timer = new Timer(500, e -> {
            splash.dispose();
            targetFrame.setVisible(true);
            this.setVisible(false);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnShowRes = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnUserProf = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnResHistory = new javax.swing.JButton();
        btnHotelList = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblSurname = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPhonenum = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblBOD = new javax.swing.JLabel();
        txtSurname = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtBirthYear = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        txtMail = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ImageIcon ppresim = new ImageIcon("/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/manstock.png");
        Image imgPP = ppresim.getImage();
        Image scaledPP = imgPP.getScaledInstance(200, 250, Image.SCALE_SMOOTH); // Genişlik ve yükseklik değerlerini belirleyin
        ImageIcon finalPP = new ImageIcon(scaledPP);
        icnProfilePhoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservations = new javax.swing.JTable();
        btnShowResHistory = new javax.swing.JButton();
        btnChangeProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnShowRes.setText("Show Reservations");
        btnShowRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowResActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnUserProf.setText("User Settings");
        btnUserProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserProfActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnResHistory.setText("Reservation History");
        btnResHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResHistoryActionPerformed(evt);
            }
        });

        btnHotelList.setText("Hotel List");
        btnHotelList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome)
                .addGap(52, 52, 52)
                .addComponent(btnHotelList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserProf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowRes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResHistory)
                .addGap(137, 137, 137)
                .addComponent(btnLogOut))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHotelList)
                        .addComponent(btnHome)
                        .addComponent(btnUserProf)
                        .addComponent(btnShowRes)
                        .addComponent(btnResHistory))
                    .addComponent(btnLogOut))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 248));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSurname.setText("Surname :");

        lblName.setText("Name :");

        lblUserName.setText("Username :");

        lblPhonenum.setText("Phone :");

        lblAddress.setText("Address :");

        lblGender.setText("Gender :");

        lblMail.setText("Mail :");

        lblBOD.setText("Birth Year :");

        txtSurname.setText("jLabel1");

        txtName.setText("jLabel2");

        txtBirthYear.setText("jLabel3");

        txtGender.setText("jLabel4");

        txtMail.setText("jLabel1");

        txtPhoneNum.setText("jLabel1");

        txtAddress.setText("jLabel1");

        jLabel9.setText("Loyalty Point :");

        txtUserName.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtName))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBOD)
                                        .addComponent(lblMail))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMail)
                                        .addComponent(txtBirthYear)
                                        .addComponent(txtPhoneNum))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhonenum)
                                    .addComponent(lblAddress))
                                .addGap(18, 18, 18)
                                .addComponent(txtAddress)))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGender))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblSurname)
                                .addGap(18, 18, 18)
                                .addComponent(txtSurname)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblSurname)
                    .addComponent(txtSurname)
                    .addComponent(txtName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBOD)
                    .addComponent(lblGender)
                    .addComponent(txtBirthYear)
                    .addComponent(txtGender))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMail)
                    .addComponent(txtMail))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhonenum)
                    .addComponent(txtPhoneNum))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        icnProfilePhoto.setIcon(finalPP);
        icnProfilePhoto.setText(null);
        jPanel4.add(icnProfilePhoto, java.awt.BorderLayout.CENTER);
        icnProfilePhoto.setHorizontalAlignment(SwingConstants.CENTER); // Ortalansın
        icnProfilePhoto.setVerticalAlignment(SwingConstants.CENTER);
        icnProfilePhoto.setPreferredSize(new java.awt.Dimension(200, 200)); // Kutu boyutları
        icnProfilePhoto.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.LIGHT_GRAY, 1)); // Çerçeve eklemek için

        tableReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableReservations);

        btnShowResHistory.setText("<html>Show Reservation History</html>");

        btnChangeProfile.setText("Change Profile");
        btnChangeProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowResHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChangeProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowResHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowResActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            String localImagePath = "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png";
            ImageIcon icon = new ImageIcon(new ImageIcon(localImagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        JLabel splashLabel = new JLabel("Loading Home...", JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);
        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);
        Timer timer = new Timer(100, e -> {
            FrameHome hotelMenuFrame = new FrameHome();
            hotelMenuFrame.setVisible(true);
            this.setVisible(false);
            splash.dispose();
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnUserProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserProfActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            String localImagePath = "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png";
            ImageIcon icon = new ImageIcon(new ImageIcon(localImagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        JLabel splashLabel = new JLabel("Logging Out...", JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);
        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);
        Timer timer = new Timer(500, e -> {
            FrameLogin loginMenu = new FrameLogin();
            loginMenu.setVisible(true);
            this.setVisible(false);
            splash.dispose();
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHotelListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelListActionPerformed
        // TODO add your handling code here:
        JWindow splash = new JWindow();
        JPanel splashPanel = new JPanel();
        splashPanel.setLayout(new BoxLayout(splashPanel, BoxLayout.Y_AXIS));
        splashPanel.setBackground(java.awt.Color.WHITE);

        JLabel iconLabel = new JLabel();
        try {
            String localImagePath = "/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/pngegg.png";
            ImageIcon icon = new ImageIcon(new ImageIcon(localImagePath).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            iconLabel.setIcon(icon);
        } catch (Exception e) {
            iconLabel.setText("Icon Cannot Loaded");
        }
        iconLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        JLabel splashLabel = new JLabel("Loading Hotel List...", JLabel.CENTER);
        splashLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        splashLabel.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 20)));
        splashPanel.add(iconLabel);
        splashPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        splashPanel.add(splashLabel);
        splash.getContentPane().add(splashPanel);
        splash.setSize(300, 200);
        splash.setLocationRelativeTo(null);
        splash.setVisible(true);
        Timer timer = new Timer(100, e -> {
            FrameHotelList hotelListFrame = new FrameHotelList();
            hotelListFrame.setVisible(true);
            this.setVisible(false);
            splash.dispose();
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnHotelListActionPerformed

    private void btnResHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResHistoryActionPerformed

    private void btnChangeProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeProfileActionPerformed
        // TODO add your handling code here:
        String[] currentUserData = {
            txtUserName.getText(),
            txtName.getText(),
            txtSurname.getText(),
            txtBirthYear.getText(),
            txtMail.getText(),
            txtPhoneNum.getText(),
            txtAddress.getText(),
            txtGender.getText()
        };

        // FrameChangeProfile penceresini oluştur ve kullanıcı verilerini aktar
        FrameChangeProfile userSettingsFrame = new FrameChangeProfile(currentUserData);

        // FrameChangeProfile penceresini görünür yap ve işlemleri bekle
        userSettingsFrame.setVisible(true);

        // Pencere kapandıktan sonra güncellemeleri al

    }//GEN-LAST:event_btnChangeProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MacOS".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeProfile;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHotelList;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnResHistory;
    private javax.swing.JButton btnShowRes;
    private javax.swing.JButton btnShowResHistory;
    private javax.swing.JButton btnUserProf;
    private javax.swing.JLabel icnProfilePhoto;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBOD;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhonenum;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tableReservations;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtBirthYear;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtMail;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPhoneNum;
    private javax.swing.JLabel txtSurname;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables
}
