/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.izzettinozmen.hotelreservation;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author ifozmen
 */
public class FrameChangeProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserSettings
     */
    public FrameChangeProfile() {
        initComponents();
        setLocationRelativeTo(null);
        populateYearComboBox();
    }

    private String[] userData;

    /**
     * Creates new form UserSettings
     */
    public FrameChangeProfile(String[] userData) {
        initComponents();
        setLocationRelativeTo(null);
        this.userData = userData;

        populateYearComboBox();
        initializeFields();
    }

    private void initializeFields() {
        // Kullanıcı verilerini TextField'lara ve diğer alanlara doldur
        if (userData[0] != null) {
            txtUserName.setText(userData[0]);
        }
        if (userData[1] != null) {
            txtName.setText(userData[1]);
        }
        if (userData[2] != null) {
            txtSurname.setText(userData[2]);
        }
        if (userData[3] != null) {
            cmbYear.setSelectedItem(userData[3]);
        }
        if (userData[4] != null) {
            txtMail.setText(userData[4]);
        }
        if (userData[5] != null) {
            txtPhoneNum.setText(userData[5]);
        }
        if (userData[6] != null) {
            txtAddress.setText(userData[6]);
        }
        if (userData[7] != null) {
            cmbGender.setSelectedItem(userData[7]);
        }

        // Placeholder'ları ekle
        setPlaceholder(txtUserName, "Enter your username");
        setPlaceholder(txtName, "Enter your first name");
        setPlaceholder(txtSurname, "Enter your surname");
        setPlaceholder(txtMail, "Enter your email address");
        setPlaceholder(txtPhoneNum, "Enter your phone number");
        setPlaceholder(txtAddress, "Enter your address");
    }

    private void populateYearComboBox() {
        int startYear = 1920;
        int currentYear = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
        cmbYear.removeAllItems();
        for (int year = startYear; year <= currentYear; year++) {
            cmbYear.addItem(String.valueOf(year));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblSurname = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPhonenum = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblBOD = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        btnConfirmSettings = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbYear = new javax.swing.JComboBox<>();
        txtAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSurname.setText("Surname :");

        lblName.setText("Name :");

        lblUserName.setText("Username :");

        lblPhonenum.setText("Phone :");

        lblAddress.setText("Address :");

        lblGender.setText("Gender :");

        lblMail.setText("Mail :");

        lblBOD.setText("Birth Year :");

        txtUserName.setToolTipText("<html>Enter Username</html>");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        btnConfirmSettings.setText("Confirm Changes");
        btnConfirmSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSettingsActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMail)
                            .addComponent(lblName)
                            .addComponent(lblAddress)
                            .addComponent(lblSurname))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(txtSurname))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblGender)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblBOD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtAddress)
                            .addComponent(txtMail)
                            .addComponent(txtPhoneNum)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUserName)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPhonenum, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmSettings)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBOD)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSurname)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMail)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhonenum)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnConfirmSettings))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setPlaceholder(JTextField textField, String placeholder) {
        if (textField.getText().isEmpty() || textField.getText().equals(placeholder)) {
            textField.setText(placeholder);
            textField.setForeground(Color.GRAY);
        }

        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }
    private void btnConfirmSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSettingsActionPerformed
        // TODO add your handling code here:
        boolean valid = true;

        // Placeholderları kontrol etmeden önce kaldır
        if (txtUserName.getText().equals("Enter your username")) {
            txtUserName.setText("");
        }
        if (txtName.getText().equals("Enter your first name")) {
            txtName.setText("");
        }
        if (txtSurname.getText().equals("Enter your surname")) {
            txtSurname.setText("");
        }
        if (txtMail.getText().equals("Enter your email address")) {
            txtMail.setText("");
        }
        if (txtPhoneNum.getText().equals("Enter your phone number")) {
            txtPhoneNum.setText("");
        }
        if (txtAddress.getText().equals("Enter your address")) {
            txtAddress.setText("");
        }

        // Alanların doğruluğunu kontrol et
        if (txtUserName.getText().isEmpty()) {
            txtUserName.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            valid = false;
        } else {
            txtUserName.setBorder(UIManager.getBorder("TextField.border"));
        }

        if (txtName.getText().isEmpty()) {
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            valid = false;
        } else {
            txtName.setBorder(UIManager.getBorder("TextField.border"));
        }

        if (txtSurname.getText().isEmpty()) {
            txtSurname.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            valid = false;
        } else {
            txtSurname.setBorder(UIManager.getBorder("TextField.border"));
        }

        if (cmbYear.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a valid birth year.", "Error", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }

        if (txtMail.getText().isEmpty()) {
            txtMail.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            valid = false;
        } else {
            txtMail.setBorder(UIManager.getBorder("TextField.border"));
        }

        if (txtPhoneNum.getText().isEmpty()) {
            txtPhoneNum.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            valid = false;
        } else {
            txtPhoneNum.setBorder(UIManager.getBorder("TextField.border"));
        }

        if (txtAddress.getText().isEmpty()) {
            txtAddress.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            valid = false;
        } else {
            txtAddress.setBorder(UIManager.getBorder("TextField.border"));
        }

        if (!valid) {
            JOptionPane.showMessageDialog(this, "Please fill in the missing fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Eğer tüm alanlar doğruysa eski verileri güncelle
        userData[0] = txtUserName.getText();
        userData[1] = txtName.getText();
        userData[2] = txtSurname.getText();
        userData[3] = (String) cmbYear.getSelectedItem();
        userData[4] = txtMail.getText();
        userData[5] = txtPhoneNum.getText();
        userData[6] = txtAddress.getText();
        userData[7] = (String) cmbGender.getSelectedItem();

        JOptionPane.showMessageDialog(this, "User settings updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();


    }//GEN-LAST:event_btnConfirmSettingsActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Cancel without saving changes?",
                "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); // Pencereyi kapat
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameChangeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameChangeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameChangeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameChangeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        String[] userData = {
            "johndoe", "John", "Doe", "1990", "john.doe@mail.com", "555-1234", "123 Main Street, NY", "Male"
        };

        java.awt.EventQueue.invokeLater(() -> {
            new FrameChangeProfile(userData).setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirmSettings;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBOD;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhonenum;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
