/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.izzettinozmen.hotelreservation;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ifozmen
 */
public class FrameMenuBackup extends javax.swing.JFrame {

    /**
     * Creates new form HotelMenu
     */
    public FrameMenuBackup() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ImageIcon otel2resim = new ImageIcon("/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/otel2.jpg");
        Image imgotel2 = otel2resim.getImage();
        Image scaledImg2 = imgotel2.getScaledInstance(200, 150, Image.SCALE_SMOOTH); // Genişlik ve yükseklik değerlerini belirleyin
        ImageIcon kucukResim2 = new ImageIcon(scaledImg2);
        iconHotel2 = new javax.swing.JLabel();
        txtHotel2 = new javax.swing.JLabel();
        txtDescHotel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRatingHotel2 = new javax.swing.JLabel();
        txtPriceHotel2 = new javax.swing.JLabel();
        btnHotel2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtHotel1 = new javax.swing.JLabel();
        ImageIcon otel1resim = new ImageIcon("/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/otel1.jpg");
        Image imgotel1 = otel1resim.getImage();
        Image scaledImg1 = imgotel1.getScaledInstance(200, 150, Image.SCALE_SMOOTH); // Genişlik ve yükseklik değerlerini belirleyin
        ImageIcon kucukResim1 = new ImageIcon(scaledImg1);
        iconHotel1 = new javax.swing.JLabel();
        txtDescHotel1 = new javax.swing.JLabel();
        txtRatingHotel1 = new javax.swing.JLabel();
        txtPriceHotel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnHotel1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ImageIcon otel3resim = new ImageIcon("/Users/ifozmen/NetBeansProjects/hotelreservation/src/main/java/com/izzettinozmen/hotelreservation/Hotels/otel3.jpg");
        Image imgotel3 = otel3resim.getImage();
        Image scaledImg3 = imgotel3.getScaledInstance(200, 150, Image.SCALE_SMOOTH); // Genişlik ve yükseklik değerlerini belirleyin
        ImageIcon kucukResim3 = new ImageIcon(scaledImg3);
        iconHotel3 = new javax.swing.JLabel();
        txtHotel3 = new javax.swing.JLabel();
        txtDescHotel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRatingHotel3 = new javax.swing.JLabel();
        txtPriceHotel3 = new javax.swing.JLabel();
        btnHotel3 = new javax.swing.JButton();
        txtFOZGO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 648));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 248));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("LiHei Pro", 0, 24)); // NOI18N
        jButton2.setText("Show More");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 690, -1, -1));

        txtWelcome.setFont(new java.awt.Font("Lantinghei TC", 3, 18)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(0, 51, 51));
        txtWelcome.setText("Welcome FOZGO Hotel Reservation ");
        jPanel1.add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 251, 248));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));

        iconHotel2.setIcon(kucukResim2);
        iconHotel2.setText(null);
        iconHotel2.setPreferredSize(new java.awt.Dimension(200, 150));

        txtHotel2.setFont(new java.awt.Font("Lantinghei SC", 1, 18)); // NOI18N
        txtHotel2.setForeground(new java.awt.Color(51, 153, 255));
        txtHotel2.setText("Crystal Bay Lodge");

        txtDescHotel2.setText("<html>Lüks konfor ve tropikal atmosferin buluştuğu tatil.</html>");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Puan:");

        txtRatingHotel2.setForeground(new java.awt.Color(255, 204, 0));
        txtRatingHotel2.setText("9.1");

        txtPriceHotel2.setBackground(new java.awt.Color(0, 0, 0));
        txtPriceHotel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtPriceHotel2.setForeground(new java.awt.Color(0, 0, 0));
        txtPriceHotel2.setText("Fiyat: 1200 TL/gece");

        btnHotel2.setText("Check Hotel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(iconHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHotel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRatingHotel2))
                            .addComponent(txtDescHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPriceHotel2)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnHotel2)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHotel2)
                .addGap(18, 18, 18)
                .addComponent(txtDescHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRatingHotel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPriceHotel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnHotel2)
                .addGap(16, 16, 16))
        );

        iconHotel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconHotel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 240, 420));

        jPanel4.setBackground(new java.awt.Color(255, 251, 248));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51), java.awt.Color.yellow, new java.awt.Color(255, 255, 51)));

        txtHotel1.setFont(new java.awt.Font("Lantinghei SC", 1, 18)); // NOI18N
        txtHotel1.setForeground(new java.awt.Color(51, 153, 255));
        txtHotel1.setText("Blue Horizon Suits");

        iconHotel1.setBackground(new java.awt.Color(153, 153, 153));
        iconHotel1.setIcon(kucukResim1);
        iconHotel1.setText(null);
        iconHotel1.setPreferredSize(new java.awt.Dimension(200, 150));

        txtDescHotel1.setText("<html>Eşsiz deniz manzarasıyla huzurun yeni adresi.</html>");

        txtRatingHotel1.setForeground(new java.awt.Color(255, 204, 0));
        txtRatingHotel1.setText("9.3");

        txtPriceHotel1.setBackground(new java.awt.Color(0, 0, 0));
        txtPriceHotel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtPriceHotel1.setForeground(new java.awt.Color(0, 0, 0));
        txtPriceHotel1.setText("Fiyat: 1500 TL/gece");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Puan:");

        btnHotel1.setText("Check Hotel");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(iconHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHotel1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRatingHotel1))
                            .addComponent(txtDescHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPriceHotel1)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnHotel1)))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHotel1)
                .addGap(18, 18, 18)
                .addComponent(txtDescHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRatingHotel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPriceHotel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnHotel1)
                .addGap(14, 14, 14))
        );

        iconHotel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconHotel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, 420));

        jPanel5.setBackground(new java.awt.Color(255, 251, 248));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));

        iconHotel3.setBackground(new java.awt.Color(153, 153, 153));
        iconHotel3.setIcon(kucukResim3);
        iconHotel3.setText(null);
        iconHotel3.setPreferredSize(new java.awt.Dimension(200, 150));

        txtHotel3.setFont(new java.awt.Font("Lantinghei SC", 1, 18)); // NOI18N
        txtHotel3.setForeground(new java.awt.Color(51, 153, 255));
        txtHotel3.setText("Starlight Cove Retreat");

        txtDescHotel3.setText("<html>Zümrüt yeşili doğa ve mavinin buluştuğu eşsiz tatil.</html>");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Puan:");

        txtRatingHotel3.setForeground(new java.awt.Color(255, 204, 0));
        txtRatingHotel3.setText("9.5");

        txtPriceHotel3.setBackground(new java.awt.Color(0, 0, 0));
        txtPriceHotel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtPriceHotel3.setForeground(new java.awt.Color(0, 0, 0));
        txtPriceHotel3.setText("Fiyat: 1700 TL/gece");

        btnHotel3.setText("Check Hotel");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtHotel3))
                    .addComponent(iconHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtPriceHotel3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRatingHotel3))
                            .addComponent(txtDescHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnHotel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHotel3)
                .addGap(18, 18, 18)
                .addComponent(txtDescHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRatingHotel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPriceHotel3)
                .addGap(17, 17, 17)
                .addComponent(btnHotel3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        iconHotel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconHotel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 240, 420));

        txtFOZGO.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtFOZGO.setForeground(new java.awt.Color(61, 61, 61));
        txtFOZGO.setText("<html> Fozgo olarak size en iyi otelleri sunmaktan gurur duyuyoruz.  Tatilinizde konfor, lüks ve unutulmaz anılar için  dünyanın dört bir yanındaki en iyi seçenekleri bir araya getirdik.<br><br> <b>En iyi fiyatlar:</b> Bütçenize uygun oteller.<br> <b>Kaliteli hizmet:</b> Misafirlerimizin konforu her zaman önceliğimizdir.<br> <b>Kapsamlı seçenekler:</b> Denize sıfır otellerden şehir otellerine kadar geniş yelpazemizle hizmetinizdeyiz.<br><br> Şimdi size uygun oteli seçin ve tatilinize bir adım daha yaklaşın! </html>");
        jPanel1.add(txtFOZGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 790, 150));

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Show Reservations");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("User Profile");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Log Out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Reservation History");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton4)
                .addGap(193, 193, 193)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MacOS".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenuBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenuBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenuBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenuBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenuBackup().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHotel1;
    private javax.swing.JButton btnHotel2;
    private javax.swing.JButton btnHotel3;
    private javax.swing.JLabel iconHotel1;
    private javax.swing.JLabel iconHotel2;
    private javax.swing.JLabel iconHotel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtDescHotel1;
    private javax.swing.JLabel txtDescHotel2;
    private javax.swing.JLabel txtDescHotel3;
    private javax.swing.JLabel txtFOZGO;
    private javax.swing.JLabel txtHotel1;
    private javax.swing.JLabel txtHotel2;
    private javax.swing.JLabel txtHotel3;
    private javax.swing.JLabel txtPriceHotel1;
    private javax.swing.JLabel txtPriceHotel2;
    private javax.swing.JLabel txtPriceHotel3;
    private javax.swing.JLabel txtRatingHotel1;
    private javax.swing.JLabel txtRatingHotel2;
    private javax.swing.JLabel txtRatingHotel3;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
